# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'money' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for money

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Functions', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  # pod 'Firebase/Invites', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'Firebase/RemoteConfig', '~> 5.11.0'
  pod 'Firebase/Storage', '~> 5.11.0'
  pod 'Firebase/Performance', '~> 5.11.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Add new pods below this line
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'


end
