(function(e){e.fn.yiiActiveForm=function(a){return h[a]?h[a].apply(this,Array.prototype.slice.call(arguments,1)):"object"!==typeof a&&a?(e.error("Method "+a+" does not exist on jQuery.yiiActiveForm"),!1):h.init.apply(this,arguments)};var z={encodeErrorSummary:!0,errorSummary:".error-summary",validateOnSubmit:!0,errorCssClass:"has-error",successCssClass:"has-success",validatingCssClass:"validating",ajaxParam:"ajax",ajaxDataType:"json",validationUrl:void 0,scrollToError:!0,scrollToErrorOffset:0,validationStateOn:"container"},
v={id:void 0,name:void 0,container:void 0,input:void 0,error:".help-block",encodeError:!0,validateOnChange:!0,validateOnBlur:!0,validateOnType:!1,validationDelay:500,enableAjaxValidation:!1,validate:void 0,status:0,cancelled:!1,value:void 0,updateAriaInvalid:!0},p,q=function(a){p&&(p.resolve(),p=void 0,a.removeData("yiiSubmitFinalizePromise"))},h={init:function(a,b){return this.each(function(){var c=e(this);if(!c.data("yiiActiveForm")){var d=e.extend({},z,b||{});void 0===d.validationUrl&&(d.validationUrl=
c.attr("action"));e.each(a,function(b){a[b]=e.extend({value:n(c,this)},v,this);w(c,a[b])});c.data("yiiActiveForm",{settings:d,attributes:a,submitting:!1,validated:!1,options:A(c)});c.on("reset.yiiActiveForm",h.resetForm);d.validateOnSubmit&&(c.on("mouseup.yiiActiveForm keyup.yiiActiveForm",":submit",function(){c.data("yiiActiveForm").submitObject=e(this)}),c.on("submit.yiiActiveForm",h.submitForm));d=e.Event("afterInit");c.trigger(d)}})},add:function(a){var b=e(this);a=e.extend({value:n(b,a)},v,a);
b.data("yiiActiveForm").attributes.push(a);w(b,a)},remove:function(a){var b=e(this),c=b.data("yiiActiveForm").attributes,d=-1,f=void 0;e.each(c,function(b){if(c[b].id==a)return d=b,f=c[b],!1});0<=d&&(c.splice(d,1),m(b,f).off(".yiiActiveForm"));return f},validateAttribute:function(a){a=h.find.call(this,a);void 0!=a&&r(e(this),a,!0)},find:function(a){var b=e(this).data("yiiActiveForm").attributes,c=void 0;e.each(b,function(d){if(b[d].id==a)return c=b[d],!1});return c},destroy:function(){return this.each(function(){e(this).off(".yiiActiveForm");
e(this).removeData("yiiActiveForm")})},data:function(){return this.data("yiiActiveForm")},validate:function(a){a&&(e(this).data("yiiActiveForm").submitting=!0);var b=e(this),c=b.data("yiiActiveForm"),d=!1,f={},k=B(),g=c.submitting;if(g&&(a=e.Event("beforeValidate"),b.trigger(a,[f,k]),!1===a.result)){c.submitting=!1;q(b);return}e.each(c.attributes,function(){this.$form=b;var a=m(b,this);if(a.is(":disabled")||a.length&&"select"===a[0].tagName.toLowerCase()&&(!a[0].options.length||1===a[0].options.length&&
""===a[0].options[0].value))return!0;this.cancelled=!1;if(c.submitting||2===this.status||3===this.status){a=f[this.id];void 0===a&&(a=[],f[this.id]=a);var g=e.Event("beforeValidateAttribute");b.trigger(g,[this,a,k]);!1!==g.result?(this.validate&&this.validate(this,n(b,this),a,k,b),this.enableAjaxValidation&&(d=!0)):this.cancelled=!0}});e.when.apply(this,k).always(function(){for(var a in f)0===f[a].length&&delete f[a];if(d&&(e.isEmptyObject(f)||c.submitting)){a=c.submitObject;var k="&"+c.settings.ajaxParam+
"="+b.attr("id");a&&a.length&&a.attr("name")&&(k+="&"+a.attr("name")+"="+a.attr("value"));e.ajax({url:c.settings.validationUrl,type:b.attr("method"),data:b.serialize()+k,dataType:c.settings.ajaxDataType,complete:function(a,c){b.trigger("ajaxComplete",[a,c])},beforeSend:function(a,c){b.trigger("ajaxBeforeSend",[a,c])},success:function(a){null!==a&&"object"===typeof a?(e.each(c.attributes,function(){this.enableAjaxValidation&&!this.cancelled||delete a[this.id]}),t(b,e.extend(f,a),g)):t(b,f,g)},error:function(){c.submitting=
!1;q(b)}})}else c.submitting?window.setTimeout(function(){t(b,f,g)},200):t(b,f,g)})},submitForm:function(){var a=e(this),b=a.data("yiiActiveForm");if(b.validated){b.submitting=!1;var c=e.Event("beforeSubmit");a.trigger(c);if(!1===c.result)return b.validated=!1,q(a),!1;b=a.data("yiiActiveForm").submitObject||a.find(":submit:first");b.length&&"submit"==b.attr("type")&&b.attr("name")&&(c=e('input[type="hidden"][name="'+b.attr("name")+'"]',a),c.length?c.attr("value",b.attr("value")):e("<input>").attr({type:"hidden",
name:b.attr("name"),value:b.attr("value")}).appendTo(a));return!0}p=e.Deferred();a.data("yiiSubmitFinalizePromise",p.promise());void 0!==b.settings.timer&&clearTimeout(b.settings.timer);b.submitting=!0;h.validate.call(a);return!1},resetForm:function(){var a=e(this),b=a.data("yiiActiveForm");window.setTimeout(function(){e.each(b.attributes,function(){this.value=n(a,this);this.status=0;var c=a.find(this.container),d=m(a,this);("input"===b.settings.validationStateOn?d:c).removeClass(b.settings.validatingCssClass+
" "+b.settings.errorCssClass+" "+b.settings.successCssClass);c.find(this.error).html("")});a.find(b.settings.errorSummary).hide().find("ul").html("")},1)},updateMessages:function(a,b){var c=e(this),d=c.data("yiiActiveForm");e.each(d.attributes,function(){u(c,this,a)});b&&x(c,a)},updateAttribute:function(a,b){var c=h.find.call(this,a);if(void 0!=c){var d={};d[a]=b;u(e(this),c,d)}}},w=function(a,b){var c=m(a,b);if(b.validateOnChange)c.on("change.yiiActiveForm",function(){r(a,b,!1)});if(b.validateOnBlur)c.on("blur.yiiActiveForm",
function(){0!=b.status&&1!=b.status||r(a,b,!0)});if(b.validateOnType)c.on("keyup.yiiActiveForm",function(c){-1===e.inArray(c.which,[16,17,18,37,38,39,40])&&b.value!==n(a,b)&&r(a,b,!1,b.validationDelay)})},r=function(a,b,c,d){var f=a.data("yiiActiveForm");c&&(b.status=2);e.each(f.attributes,function(){var b=this.value,d=n(a,this);if(b instanceof Object)b=C(b,d);else if(Array.isArray(b))b:if(Array.isArray(b)&&Array.isArray(d)&&b.length===d.length){for(var e=0;e<b.length;e+=1)if(b[e]!==d[e]){b=!1;break b}b=
!0}else b=!1;else b=b===d;b||(this.status=2,c=!0)});c&&(void 0!==f.settings.timer&&clearTimeout(f.settings.timer),f.settings.timer=window.setTimeout(function(){f.submitting||a.is(":hidden")||(e.each(f.attributes,function(){2===this.status&&(this.status=3,a.find(this.container).addClass(f.settings.validatingCssClass))}),h.validate.call(a))},d?d:200))},C=function(a,b){if(!(a instanceof Object&&b instanceof Object))return!1;var c=Object.keys(a),d=Object.keys(b);if(c.length!==d.length)return!1;for(d=
0;d<c.length;d+=1)if(!b.hasOwnProperty(c[d])||a[c[d]]!==b[c[d]])return!1;return!0},B=function(){var a=[];a.add=function(b){this.push(new e.Deferred(b))};return a},l=["action","target","method","enctype"],A=function(a){for(var b={},c=0;c<l.length;c++)b[l[c]]=a.attr(l[c]);return b},D=function(a,b){for(var c=0;c<l.length;c++){var d=b.attr("form"+l[c]);d&&a.attr(l[c],d)}},E=function(a){for(var b=a.data("yiiActiveForm"),c=0;c<l.length;c++)a.attr(l[c],b.options[l[c]]||null)},t=function(a,b,c){var d=a.data("yiiActiveForm");
if(void 0===d)return!1;var f=[],k;e.each(d.attributes,function(){var d=c&&u(a,this,b)||!c&&y(a,this,b);k=m(a,this);k.is(":disabled")||this.cancelled||!d||f.push(this)});a.trigger("afterValidate",[b,f]);if(c)if(x(a,b),f.length){if(d.settings.scrollToError){var g=a.find(e.map(f,function(b){return b.input}).join(",")).first().closest(":visible").offset().top-d.settings.scrollToErrorOffset;0>g?g=0:g>e(document).height()&&(g=e(document).height());var h=e(window).scrollTop();(g<h||g>h+e(window).height())&&
e(window).scrollTop(g)}d.submitting=!1}else d.validated=!0,d.submitObject&&D(a,d.submitObject),a.submit(),d.submitObject&&E(a);else e.each(d.attributes,function(){this.cancelled||2!==this.status&&3!==this.status||u(a,this,b)});q(a)},u=function(a,b,c){var d=a.data("yiiActiveForm"),f=m(a,b),k=y(a,b,c);e.isArray(c[b.id])||(c[b.id]=[]);b.status=1;if(f.length){var g=a.find(b.container),h=g.find(b.error);b.updateAriaInvalid&&a.find(b.input).attr("aria-invalid",k?"true":"false");f="input"===d.settings.validationStateOn?
f:g;k?(b.encodeError?h.text(c[b.id][0]):h.html(c[b.id][0]),f.removeClass(d.settings.validatingCssClass+" "+d.settings.successCssClass).addClass(d.settings.errorCssClass)):(h.empty(),f.removeClass(d.settings.validatingCssClass+" "+d.settings.errorCssClass+" ").addClass(d.settings.successCssClass));b.value=n(a,b)}a.trigger("afterValidateAttribute",[b,c[b.id]]);return k},y=function(a,b,c){a=m(a,b);var d=!1;e.isArray(c[b.id])||(c[b.id]=[]);a.length&&(d=0<c[b.id].length);return d},x=function(a,b){var c=
a.data("yiiActiveForm"),d=a.find(c.settings.errorSummary),f=d.find("ul").empty();d.length&&b&&(e.each(c.attributes,function(){if(e.isArray(b[this.id])&&b[this.id].length){var a=e("<li/>");c.settings.encodeErrorSummary?a.text(b[this.id][0]):a.html(b[this.id][0]);f.append(a)}}),d.toggle(0<f.find("li").length))},n=function(a,b){var c=m(a,b),d=c.attr("type");return"checkbox"===d||"radio"===d?(d=c.filter(":checked"),d.length||(d=a.find('input[type=hidden][name="'+c.attr("name")+'"]')),d.val()):c.val()},
m=function(a,b){var c=a.find(b.input);return c.length&&"div"===c[0].tagName.toLowerCase()?c.find("input"):c}})(window.jQuery);